package com.randomnoun.common.jessop;

import javax.script.ScriptContext;
import javax.script.ScriptException;

/** The only reason this thing exists is because the 'bsh' and 'luaj' script engines 
 * don't throw ScriptExceptions properly
 *  
 * @author knoxg
 * @version $Id$
 */
public interface JessopExceptionConverter {

	/** Convert runtime exceptions generated by this language's ScriptEngine into ScriptExceptions.
	 * 
	 * <p>(Most languages do this properly already, except for lua).
	 * 
	 * <p>This is called at runtime, not target script generation time, and should be 
	 * associated with the target source engine (e.g. rhino), not the target language (e.g. javascript),
	 * but I didn't want to create another interface just for this.
	 */
	ScriptException toScriptException(ScriptContext scriptContext, Throwable t);

}
