package com.randomnoun.common.jessop;

/* (c) 2016 randomnoun. All Rights Reserved. This work is licensed under a
 * BSD Simplified License. ( http://www.randomnoun.com/bsd-simplified.html ) 
 */

import javax.script.ScriptContext;
import javax.script.ScriptException;

/** The only reason this thing exists is because the 'bsh' and 'luaj' script engines 
 * don't throw ScriptExceptions properly
 *  
 * @author knoxg
 */
public interface JessopExceptionConverter {

	/** Convert runtime exceptions generated by this language's ScriptEngine into ScriptExceptions.
	 * 
	 * <p>(Most languages do this properly already, except for lua).
	 * 
	 * <p>This is called at runtime, not target script generation time, and should be 
	 * associated with the target source engine (e.g. rhino), not the target language (e.g. javascript).
	 */
	ScriptException toScriptException(ScriptContext scriptContext, Throwable t);

}
